name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
jobs:

  install:
    runtime-versions:
      python: 3.9
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name test --zip-file lambda_function.zip
      - echo "DONE!!"
